#!/usr/bin/env python3
import csv
import datetime
import requests
import operator


FILE_URL="http://marga.com.ar/employees-with-date.csv"

def get_start_date():
    """Interactively get the start date to query for."""

    print()
    print('Getting the first start date to query for.')
    print()
    print('The date must be greater than Jan 1st, 2018')
    year = int(input('Enter a value for the year: '))
    month = int(input('Enter a value for the month: '))
    day = int(input('Enter a value for the day: '))
    print()

    return str(datetime.datetime(year, month, day).date())

def get_file_lines(url):
    """Returns the lines contained in the file at the given URL"""

    # Download the file over the internet
    response = requests.get(url, stream=True)

    # Decode all lines into strings
    lines = []
    for line in response.iter_lines():
        lines.append(line.decode("UTF-8"))
    return lines

def get_same_or_newer(start_date):
    FILE_URL = "http://marga.com.ar/employees-with-date.csv"
    data = get_file_lines(FILE_URL)
    reader = csv.reader(data[1:])
    sortedlist = sorted(reader, key=operator.itemgetter(3))
    for row in sortedlist:
        row_date = datetime.datetime.strptime(row[3], '%Y-%m-%d').strftime("%b %d, %Y")
        #print(type(row[3]), type(start_date))
        employee = [row[0] + " " + row[1]]
        if row[3] >= start_date:
            print("Started on {}: {}".format(row_date, employee))

def main():
    start_date = get_start_date()
    get_same_or_newer(start_date)

if __name__ == "__main__":
    main()
